/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DiaryCard: typeof import('./src/components/diary/DiaryCard.vue')['default']
    EmptyStates: typeof import('./src/components/EmptyStates.vue')['default']
    FloatingactionButtons: typeof import('./src/components/FloatingactionButtons.vue')['default']
    InfoCard: typeof import('./src/components/InfoCard.vue')['default']
    IssueCard: typeof import('./src/components/IssueCard.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RestaurantCard: typeof import('./src/components/restaurant/RestaurantCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperCarousel: typeof import('./src/components/SwiperCarousel.vue')['default']
    VisionCard: typeof import('./src/components/VisionCard.vue')['default']
  }
}
